// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxkjS5Zzabc8JKS4C5nOxlJdLphoU_hoA',
    appId: '1:7156448061:web:cdb810adc1a69d7b41e354',
    messagingSenderId: '7156448061',
    projectId: 'my-name-3664d',
    authDomain: 'my-name-3664d.firebaseapp.com',
    storageBucket: 'my-name-3664d.appspot.com',
    measurementId: 'G-R8XK90K2EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn4FZZRejPRot1FVWP4v6R1OZ_s7UB5DU',
    appId: '1:7156448061:android:a609407c91fe8fa941e354',
    messagingSenderId: '7156448061',
    projectId: 'my-name-3664d',
    storageBucket: 'my-name-3664d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA048-9A34jYAGFDXDKET70rjqhqhIFv5k',
    appId: '1:7156448061:ios:dde11eeafed2382541e354',
    messagingSenderId: '7156448061',
    projectId: 'my-name-3664d',
    storageBucket: 'my-name-3664d.appspot.com',
    iosBundleId: 'com.example.myNote',
  );
}
